// Arma design/pdf/maqueta-rescate.html con el mismo estilo (CSS y garabatos) de maqueta-metodo.html.
const fs = require('fs');
const DIR = 'C:/Users/jahen/RachaX/RachaX/design/pdf';
const base = fs.readFileSync(DIR + '/maqueta-metodo.html', 'utf8');
const corte = base.indexOf('<!-- 1 -->');
if (corte < 0) throw new Error('no encontré el inicio de las páginas');
let cabeza = base.slice(0, corte).replace('<title>Método Anti-Abandono · maqueta (estilo cómic)</title>', '<title>Protocolo de Rescate</title>');
const extra = [
  '/* Protocolo de Rescate */',
  '.paso{display:flex;gap:12px;align-items:flex-start;padding:8px 12px;margin:0 6px 11px 0!important}',
  '.paso .ic{flex:none;width:44px;height:44px;border-radius:50%;background:var(--ambar);border:2.5px solid var(--ink);box-shadow:0 0 0 2px var(--ambar);display:grid;place-items:center;position:relative}',
  '.paso .ic em{position:absolute;left:-7px;top:-7px;width:20px;height:20px;border-radius:50%;background:var(--papel);color:var(--ink);border:2px solid var(--ink);font-style:normal;font-weight:700;font-size:12px;display:grid;place-items:center}',
  '.paso p{margin:0!important;font-size:13.5px;line-height:1.33}',
  '.paso p b{display:block;font-size:14.5px;text-transform:uppercase;letter-spacing:.01em;margin-bottom:1px}',
  '.fl{display:flex;flex-direction:column;align-items:center;gap:0;margin:0 6px 14px 0}',
  '.fl .bx{width:100%;border:2.5px solid var(--text);border-radius:6px;background:var(--sup);padding:8px 12px;font-weight:700;font-size:14.5px;text-align:center;box-shadow:5px 5px 0 var(--ambar)}',
  '.fl .bx.am{background:var(--ambar);color:var(--ink);border-color:var(--ink);box-shadow:0 0 0 2.5px var(--ambar);width:auto;padding:8px 22px;border-radius:22px;text-transform:uppercase;transform:rotate(-1.5deg)}',
  '.fl .bx small{display:block;font-weight:600;font-size:12px;color:var(--muted)}',
  '.fl .fle{width:3px;height:16px;background:var(--ambar);position:relative;margin:5px 0 7px}',
  '.fl .fle:after{content:"";position:absolute;left:-5px;bottom:-5px;border:6.5px solid transparent;border-top-color:var(--ambar);border-bottom:0}',
  '.fl .dos{display:flex;gap:10px;width:100%;margin-top:8px}',
  '.fl .dos .bx{font-size:13px;padding:7px 8px;box-shadow:none}',
  '.fl .dos .bx.li{border-color:var(--lila);background:var(--lilabg)}',
  '.lt.min li i{font-size:13px}',
  '[data-img="r2-revision"] img{object-position:50% 22%}',
  '.r3 td{padding:6px 8px 6px 0}',
  '.r3 table{font-size:13px}',
  '.r3 .vin{margin-bottom:14px!important}',
  '.r3 .app{padding:8px 12px}',
  '</style>',
].join('\n');
cabeza = cabeza.replace('</style>', extra);
const dd = '  <svg class="dd" viewBox="0 0 390 693"><use href="#garab" stroke="rgba(255,255,255,.055)"/></svg><div class="pts"></div>';
const pie = (n) => '  <span class="pie">Protocolo de Rescate</span><span class="num">' + n + '</span>';
const ic = {
  no: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#0F1113" stroke-width="2.6" stroke-linecap="round"><circle cx="12" cy="12" r="9"/><path d="M5.6 5.6l12.800 12.800"/></svg>',
  escudo: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#0F1113" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 3v6c0 5-3.500 8-8 9-4.500-1-8-4-8-9V6z"/></svg>',
  check: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#0F1113" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12.500l5 5L20 6.500"/></svg>',
  sol: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#0F1113" stroke-width="2.6" stroke-linecap="round"><path d="M5 18a7 7 0 0 1 14 0M2 18h20M12 4v3M4.500 8.500l2 2M19.500 8.500l-2 2"/></svg>',
};
const paso = (n, icono, titulo, texto) => '  <div class="vin paso"><span class="ic"><em>' + n + '</em>' + ic[icono] + '</span><p><b>' + titulo + '</b>' + texto + '</p></div>';

const paginas = [
'<!-- 1 -->',
'<section class="pg am cov">',
'  <svg class="dd" viewBox="0 0 390 693"><use href="#garab" stroke="rgba(255,255,255,.34)"/></svg>',
'  <div class="im" data-img="r1-portada"><b>IMAGEN 1 · portada</b>Ella, agachada, cuida con las manos<br>una llama pequeña que casi se apaga.</div>',
'  <div class="tx">',
'    <h1>Protocolo<br><span>de Rescate</span></h1>',
'    <p class="s">Qué hacer el día después de fallar.<br>En 5 minutos.</p>',
'    <div class="marca"><i><svg width="16" height="16" viewBox="0 0 24 24"><use href="#llama"/></svg></i>Racha</div>',
'  </div>',
'</section>',
'',
'<!-- 2 -->',
'<section class="pg ap" style="font-size:14.2px">',
dd,
'  <span class="tag">01 · El día después</span>',
'  <h2 class="s">Ayer fallaste. Hoy haz <mark>esto</mark></h2>',
'  <p>Son cuatro pasos y caben en cinco minutos. Hazlos en orden, sin pensarlo mucho.</p>',
paso(1, 'no', 'No hagas cuentas.', 'No mires cuánto perdiste ni cuánto te falta. Un día sin cumplir no borra los demás.'),
paso(2, 'escudo', 'Congela, si puedes.', 'Abre Racha. Si ayer quedó sin marcar y te quedan comodines, te pregunta: “¿Lo congelas?”. Di que sí.'),
paso(3, 'check', 'Haz una sola cosa, en su versión mínima.', 'Toca “¿Día pesado? Haz solo lo mínimo”, escoge el hábito más fácil y márcalo. Con eso ya volviste.'),
paso(4, 'sol', 'Deja decidido mañana.', 'Una cosa, y después de qué la vas a hacer. Nada más.'),
'  <p style="font-weight:700;margin-top:2px">Si hoy solo alcanzas a hacer el paso 3, está bien.</p>',
pie(2),
'</section>',
'',
'<!-- 3 -->',
'<section class="pg ap r3" style="font-size:13.9px">',
dd,
'  <span class="tag">02 · Más de un día</span>',
'  <h2 class="s">Si fueron <mark>varios días</mark></h2>',
'  <p>Tres días, una semana, un mes. El protocolo es el mismo, con tres cuidados.</p>',
'  <p><b>No pagues la deuda.</b> No intentes reponer lo que no hiciste. Lo de ayer ya pasó; lo de hoy es lo único que cuenta.</p>',
'  <p><b>Vuelve con uno, no con todos.</b> Si tenías tres hábitos, hoy marca uno. Los otros esperan.</p>',
'  <p><b>Si uno se cae siempre, es muy grande.</b> Achícale la versión mínima, o archívalo por un tiempo. Lo puedes restaurar cuando quieras, con su historial.</p>',
'  <div class="vin fig">',
'    <table>',
'      <tr><th style="width:50%">Lo que te provoca</th><th class="si"><span>Lo que sirve</span></th></tr>',
'      <tr><td class="no">Reponer todo hoy</td><td class="si">Hacer una sola cosa</td></tr>',
'      <tr><td class="no">Empezar de cero el lunes</td><td class="si">Volver hoy</td></tr>',
'      <tr><td class="no">Agregar hábitos para compensar</td><td class="si">Quitar uno</td></tr>',
'      <tr><td class="no">Castigarte</td><td class="si">Congelar el día y seguir</td></tr>',
'    </table>',
'  </div>',
'  <div class="app"><b>En Racha:</b> si llevabas tres días o más en blanco, el día que vuelves tus puntos valen el doble.</div>',
pie(3),
'</section>',
'',
'<!-- 4 -->',
'<section class="pg ap">',
dd,
'  <span class="tag">03 · Una vez a la semana</span>',
'  <h2>La revisión de <mark>10 minutos</mark></h2>',
'  <div class="vin img" data-img="r2-revision" style="height:126px"><b>IMAGEN 2 · la revisión</b>Ella sentada con un café, mirando el celular tranquila.</div>',
'  <p>Una vez a la semana, el mismo día. No es para juzgarte: es para ajustar.</p>',
'  <ol class="lt min">',
'    <li><i>2</i><b>2 minutos · ¿Qué sí hice?</b>Abre Tu semana y mira “Cómo vas”. Empieza por lo que salió.</li>',
'    <li><i>3</i><b>3 minutos · ¿Qué día se me cayó, y qué pasó ese día?</b>Casi siempre es el mismo día o la misma hora.</li>',
'    <li><i>2</i><b>2 minutos · ¿Qué hábito me está quedando grande?</b>Si Racha te muestra “Rescate”, ese es. Ajustarlo funciona mejor que forzarlo.</li>',
'    <li><i>3</i><b>3 minutos · ¿Qué pasos van esta semana?</b>Ponles día en Tu semana.</li>',
'  </ol>',
'  <p>Y si no sabes qué cambiar, abre Progreso y mira “Qué hacer ahora”.</p>',
pie(4),
'</section>',
'',
'<!-- 5 -->',
'<section class="pg ap">',
dd,
'  <span class="tag">04 · Para guardar</span>',
'  <h2 class="s">El protocolo en <mark>una hoja</mark></h2>',
'  <div class="fl">',
'    <div class="bx am">¿Fallaste ayer?</div><div class="fle"></div>',
'    <div class="bx">1 · No hagas cuentas</div><div class="fle"></div>',
'    <div class="bx">2 · ¿Tienes comodín?<div class="dos"><div class="bx li" style="flex:1">Sí: congélalo</div><div class="bx" style="flex:1">No: sigue igual</div></div></div><div class="fle"></div>',
'    <div class="bx">3 · Haz una sola cosa, en mínimo</div><div class="fle"></div>',
'    <div class="bx">4 · Deja decidido mañana</div>',
'  </div>',
'  <div class="app" style="text-align:center"><b>Una vez a la semana:</b> 10 minutos para ajustar.</div>',
'  <p class="fz" style="margin-top:16px">Fallar no te saca del camino. <mark>Quedarte quieto, sí.</mark></p>',
'  <span class="pie">Racha · tengoracha.com · hola@tengoracha.com</span><span class="num">5</span>',
'</section>',
'',
'</body>',
'</html>',
'',
].join('\n');
fs.writeFileSync(DIR + '/maqueta-rescate.html', cabeza + paginas);
console.log('ok');
